# Generated by Django 5.2.4 on 2025-07-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cvv',
            new_name='CVV',
        ),
    ]
