# Generated by Django 5.2.4 on 2025-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMovies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='youtube_trailer_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
